class ListsController < ApplicationController
  before_filter :is_logged_in?
  # GET /lists
  # GET /lists.xml
  def index # TODO require authentication
    session[:came_from] = :index
    @user = User.find session[:id], :include => {:lists => [:items]}
    @lists = @user.lists.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.xml
  def show # TODO require authentication
    session[:came_from] = :show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.xml
  def new # TODO require authentication
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/1/edit
  def edit # TODO require authentication
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.xml
  def create
    @list = List.new(params[:list])
    if user = User.find(session[:id])
      @list.users << user
    else
      raise 'wtf' # TODO
    end

    respond_to do |format|
      if @list.save
        format.html { redirect_to(lists_url, :notice => 'List was successfully created.') }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.xml
  def update # TODO require authentication
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(redirect_url, :notice => 'List was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.xml
  def destroy # TODO require authentication
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(lists_url) }
      format.xml  { head :ok }
    end
  end
  
############ autogenerated code ends here
  # GET /lists/1/share
  def share_form
    @user = User.new
    @list = List.find params[:id]
  end
  
  # post /lists/1/share
  def share
    @list = List.find params[:id]
    unless @user = User.find_by_email(params[:user][:email])
      @user = User.new
      @user.errors.add :email, "No user with that email." # TODO COPY make this a constant
      render "share_form"
      return
    end
    @list.users << @user
    redirect_to lists_url, :notice => "List successfully shared." # COPY
  end
end
